version: "3.8" # РІРµСЂСЃРёСЏ РІР°С€РµРіРѕ docker-compose
services:
  # РёРјРµРґР¶Рё, РєРѕС‚РѕСЂС‹Рµ Р·Р°РїСѓСЃС‚СЏС‚СЃСЏ РїРѕ РІР°С€РµРјСѓ Р¶РµР»Р°РЅРёСЋ
  db:
    # РЅР°Р·РІР°РЅРёРµ РјРѕРµРіРѕ РёРјРµРґР¶Р°
    image: postgres:12 # СЃРєР°С‡Р°РµС‚ image postgres 12 РІРµСЂСЃРёРё
    volumes:
      # С‡Р°СЃС‚СЊ РЅР°СЃС‚СЂРѕРµРє РґР»СЏ С…СЂР°РЅРµРЅРёСЏ РґР°РЅРЅС‹С…, РїРѕРєР° РґР»СЏ РЅР°СЃ СЌС‚Рѕ РЅРµ РІР°Р¶РЅРѕ
      - type: volume
        source: postgresdb-data
        target: /var/lib/postgresql/data
    ports:
      # РїРѕСЂС‚С‹
      - "5432:5432"
    environment:
      # РїРµСЂРµРјРµРЅРЅС‹Рµ РѕРєСЂСѓР¶РµРЅРёСЏ, РјРµРЅСЏР№С‚Рµ РёС… РµСЃР»Рё С…РѕС‚РёС‚Рµ РїРѕРјРµРЅСЏС‚СЊ РїР°СЂРѕР»СЊ, Р»РѕРіРёРЅ РёР»Рё РЅР°Р·РІР°РЅРёРµ СЃС‚Р°СЂС‚РѕРІРѕР№ Р±Р°Р·С‹ РґР°РЅРЅС‹С…
      POSTGRES_USER: root
      POSTGRES_DB: RIP
      POSTGRES_PASSWORD: root
  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: root
      MINIO_SECRET_KEY: rootroot
      MINIO_CONSOLE_ADDRESS: ":9001"
    volumes:
      - minio-data:/data
    command: server /data
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - redis-data:/data

volumes:
  # С‡Р°СЃС‚СЊ РЅР°СЃС‚СЂРѕРµРє РґР»СЏ С…СЂР°РЅРµРЅРёСЏ РґР°РЅРЅС‹С…
  postgresdb-data:
    driver: local
  minio-data:
    driver: local
  redis-data:
    driver: local

